/*
 * Cloudflare Calls API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppsAppIdSessionsSessionIdRenegotiatePutRequest {
    #[serde(rename = "sessionDescription", skip_serializing_if = "Option::is_none")]
    pub session_description: Option<Box<models::SessionDescription>>,
}

impl AppsAppIdSessionsSessionIdRenegotiatePutRequest {
    pub fn new() -> AppsAppIdSessionsSessionIdRenegotiatePutRequest {
        AppsAppIdSessionsSessionIdRenegotiatePutRequest {
            session_description: None,
        }
    }
}

