/*
 * Cloudflare Calls API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloseTrackObject {
    /// mid associated to the track's transceiver to close
    #[serde(rename = "mid", skip_serializing_if = "Option::is_none")]
    pub mid: Option<String>,
}

impl CloseTrackObject {
    pub fn new() -> CloseTrackObject {
        CloseTrackObject {
            mid: None,
        }
    }
}

