/*
 * Cloudflare Calls API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloseTracksResponseTracksInner {
    /// mid associated to the track's transceiver to close
    #[serde(rename = "mid", skip_serializing_if = "Option::is_none")]
    pub mid: Option<String>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<models::TracksResponseTracksInnerAllOfError>>,
}

impl CloseTracksResponseTracksInner {
    pub fn new() -> CloseTracksResponseTracksInner {
        CloseTracksResponseTracksInner {
            mid: None,
            error: None,
        }
    }
}

