/*
 * Cloudflare Calls API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TracksResponse {
    #[serde(rename = "requiresImmediateRenegotiation", skip_serializing_if = "Option::is_none")]
    pub requires_immediate_renegotiation: Option<bool>,
    #[serde(rename = "sessionDescription", skip_serializing_if = "Option::is_none")]
    pub session_description: Option<Box<models::SessionDescription>>,
    #[serde(rename = "tracks", skip_serializing_if = "Option::is_none")]
    pub tracks: Option<Vec<models::TracksResponseTracksInner>>,
}

impl TracksResponse {
    pub fn new() -> TracksResponse {
        TracksResponse {
            requires_immediate_renegotiation: None,
            session_description: None,
            tracks: None,
        }
    }
}

