/*
 * Cloudflare Calls API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TracksRequest {
    #[serde(rename = "sessionDescription", skip_serializing_if = "Option::is_none")]
    pub session_description: Option<Box<models::SessionDescription>>,
    #[serde(rename = "tracks", skip_serializing_if = "Option::is_none")]
    pub tracks: Option<Vec<models::TrackObject>>,
}

impl TracksRequest {
    pub fn new() -> TracksRequest {
        TracksRequest {
            session_description: None,
            tracks: None,
        }
    }
}

